### ISSUE TITLE
Multiple replies for a single DM.

### ISSUE THREAD

**Issue by alexandrepupo** [botmasterai/botmaster#21]
I’m trying to use Botmaster (version 0.4.1) in Node-RED, but I’m getting multiple replies for each DM the account receives.

I did the Twitter configuration following the instructions from https://github.com/botmasterai/botmaster-twitter-dm and I’m using the flow available at https://flows.nodered.org/node/node-red-contrib-botmaster.

In addition to this problem, I also get the error message “TypeError: bot.removeAllListeners is not a function” in Node-RED every time I deploy the flow.

Any suggestion on how to solve these problems?

**Comment by jwickens** [comment]
Hi @alexandrepupo sorry for your troubles, ive released a minor patch with version 0.4.2. Can you please confirm if this fixes your issue? 

As a workaround you can also restart the server to avoid double DM's. 

Also fine to leave the issue here for now but for the future if you have issues with botmaster on node-red please post them here: https://github.com/botmasterai/node-red-contrib-botmaster/issues
