### ISSUE TITLE
Add RTM in SlackBot class for status and is_typing!

### ISSUE THREAD

**Issue by jdwuarin** [botmasterai/botmaster#6]

**Comment by k7n4n5t3w4rt** [comment]
hi jdwuarin, thanks for making botmaster. i think the approach is great - just what i've been looking for. also, the website is excellent. the docs are super clear - much appreciated!

i have previously set up an app with botkit but i'd like to use botmaster, mainly because i'm specifically looking for a platform agnostic, lightweight bot layer behind which i can build out an architecture of micro-services. i did it in botkit with an array of controllers but the 'supercontroller' approach you've taken is really everything i need in one clean package. so perfect!

the Real Time Messaging API integration that botkit has is pretty neat. way simpler to set up at the Slack end with only one token needed (https://my.slack.com/services/new/bot). also, it's great being able to use it on a local URL while developing because it doesn't rely on webhooks.

I guess that's why you added this issue! this is really just a long rambling +1 but i assume it's a non-trivial implementation involving complicated socket type stuff and i thought it deserved a longer message :)

anyway, keep up the great work, it is much appreciated.

Kynan

**Comment by jdwuarin** [comment]
Hey Kynan, thanks for the message. As mentioned in another message, I am now hard at work on Botmaster 3.0 which will come with a bunch of goodies that should make your development work even easier. Once that is deployed (in a few days), I will be updating The SlackBot class/package. It will be in line with what you have mentioned here.

Thanks again for your message and your support. 

Cheers,

JD

**Comment by k7n4n5t3w4rt** [comment]
That's great news JD. Thanks!

**Comment by jdwuarin** [comment]
Moved to: https://github.com/botmasterai/botmaster-slack/issues/2
